package hygge.blog.config.database;

import hygge.commons.spring.config.configuration.HyggeSpringProperties;
import lombok.Generated;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * 数据库配置类
 *
 * @author Xavier
 * @date 2022/7/17
 */
@Getter
@Setter
@Generated
@NoArgsConstructor
@ConfigurationProperties(prefix = "hygge.blog.database")
public class DatabaseConfiguration implements HyggeSpringProperties {
    private String url;
    private String userName;
    private String password;
    private Boolean autoGenerateDdl = true;
    private Boolean showSql = true;
}
