# \u542F\u52A8\u9879\u76EE\u9700\u8981\u7684\u989D\u5916\u53C2\u6570\uFF0C\u542F\u52A8\u9879\u76EE\u65F6\u8BF7\u4ED4\u7EC6\u586B\u5145
database.password=XXXXXX
database.url=jdbc:mysql://XXXXXX:3306/hygge_blog
database.userName=root
es.password=XXXXXX
es.hostPort=XXXXXX:9200
file.expose.api.prefix=https://www.XXXXXX.com/file/
file.expose.nginx.prefix=https://www.YYYYYY.com/file/
ipquery.key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX